### ISSUE TITLE
Eigenvectors

### ISSUE THREAD

**Issue by rveltz** [RalphAS/PeriodicSchurDecompositions.jl#12]
Hi,

Is there a simple / generic way to retrieve the eigenvectors?

**Comment by RalphAS** [comment]
I have some rudimentary code for that; I'll try to bring it up to publishable standard soon.

**Comment by RalphAS** [comment]
@rveltz  I have added `eigvecs` methods in the latest release. There is some peculiar accuracy loss in the results for the Krylov-Schur version, but perhaps they are good enough for initial trials.
